name: Build dist and push to S3 bucket

on:
  create:
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: build-plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '17'
      - name: npm run build
        run: |
          npm i webpack
          npm run build
      
