name: Build dist and push to S3 bucket

on:
  create:
  
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    environment: build-plugins
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '12'
      - name: npm run build
        run: |
          npm install
          npm run build
      - name: versioning
        run: |
          echo "Run standard-version"
          npm run bump-canary
          sha=$(git rev-parse --verify --short HEAD)
          echo "Current sha ${sha}"
          commitNumberAfterTag=$(git rev-list  `git rev-list --tags --no-walk --max-count=1`..HEAD --count)
          echo "Number of commit from last tag ${commitNumberAfterTag}"
          currentVersion=$(npx -c 'echo "$npm_package_version"')
          echo "Current version ${currentVersion}"
          newVersion=$(echo $currentVersion | sed -e "s/canary\.[[:digit:]]/canary.${commitNumberAfterTag}-${sha}/g")
          echo "New version ${newVersion}"
          sed -iE "s/$currentVersion/$newVersion/g" package-lock.json
          sed -iE "s/$currentVersion/$newVersion/g" package.json
          sed -iE "s/$currentVersion/$newVersion/g" CHANGELOG.md
