## Canary CI/CD
name: Canary
run-name: Canary

on:
  push:
    branches:
      - master

jobs:
  #test:
    #uses: kaltura/playkit-js-common/.github/workflows/cypress.yml@master
    #secrets: inherit

  canary:
    if: ${{ github.actor != 'PlaykitJs-Bot' }}
    uses: kaltura/playkit-js-common/.github/workflows/canary_full_flow_plugin.yaml@da1f330989114b96e96eee60312c29f294a86cc5
    secrets: inherit
    with:
      schema-type: "playerV3OvpVersions"
      tests-yarn-run-to-execute: 'build'
      node-version: "18.x"

